baseURL = "https://rockylinux.org/"
languageCode = "en-us"
title = "Rocky Linux"
theme = "rockylinux"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  homeSubtitle = " community-driven effort bringing you enterprise-grade, production-ready Linux."


[menu]

  [[menu.main]]
    name = "Community"
    url = "community/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20

  [[menu.main]]
    name = "Download"
    url = "download/"
    weight = 15

  [[menu.main]]
    name = "Documentation"
    url = "documentation/"
    weight = 15
